# Generated by Django 4.2.7 on 2023-11-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiles',
            name='picture',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
